#!/usr/bin/env python3
import grpc
import struct
import sys
import time
import random
import base64

# Import classes generated by .proto file
import lab6_pb2
import lab6_pb2_grpc

# Service functions(borrowed from REST server)
def doRawImage(channel,debug=False):
    # Create the stub object
    stub = lab6_pb2_grpc.rawStub(channel)
    # Open image to be sent
    img = open('Flatirons_Winter_Sunrise_edit_2.jpg', 'rb').read()
    # Create the rawImageMsg object
    raw_img = lab6_pb2.rawImageMsg(img=img)
    # Get response
    response = stub.raw(raw_img)
    
    if debug:
        # decode response
        print("Response is:", response.width, response.height)

def doAdd(channel,debug=False):
    # Create the stub object
    stub = lab6_pb2_grpc.addStub(channel)
    # Create the addMsg object to be sent
    number = lab6_pb2.addMsg(a=5, b=10)
    # Get response
    response = stub.add(number)
        
    if debug:
        # decode response
        print("Response is:", response.sum)

def doDotProduct(channel,debug=False):
    # Create the stub object
    stub = lab6_pb2_grpc.dotStub(channel)
    
    #Generate 2 vectors of 100 length between 0 and 1
    a = [random.random() for _ in range(100)]
    b = [random.random() for _ in range(100)]
    
    # Create the dotProductMsg object to be sent
    vectors = lab6_pb2.dotProductMsg()
    vectors.a.extend(a)
    vectors.b.extend(b)
    response = stub.dot(vectors)
    
    if debug:
        # decode response
        print("Response is:", response.dotproduct)

def doJsonImage(channel,debug=False):
    # Create the stub object
    stub = lab6_pb2_grpc.jsonimgStub(channel)
    # Read in image as raw bytes and convert to base64 string
    img = open('Flatirons_Winter_Sunrise_edit_2.jpg', 'rb').read()
    encoded_img = base64.b64encode(img)
    encoded_string = encoded_img.decode('utf-8')
    
    # Create the jsonImageMsg object to be sent
    string_obj = lab6_pb2.jsonImageMsg(img=encoded_string)
    response = stub.jsonimg(string_obj)
    
    if debug:
        # decode response
        print("Response is:", response.width, response.height)

# Taken in input parameters based(borrowed from REST example)
if len(sys.argv) < 3:
    print(f"Usage: {sys.argv[0]} <server ip> <cmd> <reps>")
    print(f"where <cmd> is one of add, rawImage, dotProduct or jsonImage")
    print(f"and <reps> is the integer number of repititions for measurement")
    exit(1)

host = sys.argv[1]
cmd = sys.argv[2]
reps = int(sys.argv[3])

addr = f"{host}:50051"
print(f"Running {reps} reps against {addr}")

# Open a gRPC channel
channel = grpc.insecure_channel(addr)

# Check what service is being requested(borrowed from REST server)
if cmd == 'rawImage':
    start = time.perf_counter()
    for x in range(reps):
        doRawImage(channel,debug=True)
    delta = ((time.perf_counter() - start)/reps)*1000
    print("Took", delta, "ms per operation")
elif cmd == 'add':
    start = time.perf_counter()
    for x in range(reps):
        doAdd(channel,debug=True)
    delta = ((time.perf_counter() - start)/reps)*1000
    print("Took", delta, "ms per operation")
elif cmd == 'jsonImage':
    start = time.perf_counter()
    for x in range(reps):
        doJsonImage(channel,debug=True)
    delta = ((time.perf_counter() - start)/reps)*1000
    print("Took", delta, "ms per operation")
elif cmd == 'dotProduct':
    start = time.perf_counter()
    for x in range(reps):
        doDotProduct(channel,debug=True)
    delta = ((time.perf_counter() - start)/reps)*1000
    print("Took", delta, "ms per operation")
else:
    print("Unknown option:", cmd)