#!/usr/bin/env python3

import grpc
from concurrent import futures
import time
from PIL import Image
import io
import base64

# Import classes generated by .proto file
import lab6_pb2
import lab6_pb2_grpc

class rawServicer(lab6_pb2_grpc.rawServicer):
    def raw(self,request,context):
        # Make an imageReply obj
        response = lab6_pb2.imageReply()
        
        # convert the data to a PIL image type so we can extract dimensions
        try:
            ioBuffer = io.BytesIO(request.img)
            img = Image.open(ioBuffer)
            # Update an imageReply obj with info to send back to client
            response.width = img.size[0]
            response.height = img.size[1]
        except:
            response.width = 0
            response.height = 0
        
        print("Handled rawImage request")
        return response

class addServicer(lab6_pb2_grpc.addServicer):
    def add(self,request,context):
        response = lab6_pb2.addReply()
        
        response.sum = request.a + request.b
        
        print("Handled add request")
        return response

class dotServicer(lab6_pb2_grpc.dotServicer):
    def dot(self,request,context):
        response = lab6_pb2.dotProductReply()
        response.dotproduct = 0.0
        
        try:
            #print(f"Received data is a:{request.a}")
            #print(f"Received data is b:{request.b}")
            a = request.a
            b = request.b
            if len(b) == len(a):
                product = sum(a_i * b_i for a_i,b_i in zip(a,b))
                response.dotproduct = product
            else:
                print("Vectors are not he same size! Cannot compute...")
        except:
            print("Error in request")
        
        print("Handled dotProduct request")
        return response

class jsonimgServicer(lab6_pb2_grpc.jsonimgServicer):
    def jsonimg(self,request,context):
        # Make an imageReply obj
        response = lab6_pb2.imageReply()

        try:
            encoded_str = request.img
            encoded_img = base64.b64decode(encoded_str)

            ioBuffer = io.BytesIO(encoded_img)
            img = Image.open(ioBuffer)

            # Update an imageReply obj with info to send back to client
            response.width = img.size[0]
            response.height = img.size[1]
        except:
            response.width = 0
            response.height = 0
        
        print("Handled jsonImage request")
        return response

# Setup grpc server
server = grpc.server(futures.ThreadPoolExecutor(max_workers=10))

lab6_pb2_grpc.add_addServicer_to_server(addServicer(),server)
lab6_pb2_grpc.add_rawServicer_to_server(rawServicer(),server)
lab6_pb2_grpc.add_dotServicer_to_server(dotServicer(),server)
lab6_pb2_grpc.add_jsonimgServicer_to_server(jsonimgServicer(),server)

port = 50051
print(f"Starting server. Listening on port {port}")
server.add_insecure_port("[::]:50051")
server.start()
server.wait_for_termination()
