# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lab6.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nlab6.proto\"\x1a\n\x0brawImageMsg\x12\x0b\n\x03img\x18\x01 \x01(\x0c\"\x1e\n\x06\x61\x64\x64Msg\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"%\n\rdotProductMsg\x12\t\n\x01\x61\x18\x01 \x03(\x02\x12\t\n\x01\x62\x18\x02 \x03(\x02\"\x1b\n\x0cjsonImageMsg\x12\x0b\n\x03img\x18\x01 \x01(\t\"\x17\n\x08\x61\x64\x64Reply\x12\x0b\n\x03sum\x18\x01 \x01(\x05\"%\n\x0f\x64otProductReply\x12\x12\n\ndotproduct\x18\x01 \x01(\x02\"+\n\nimageReply\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x32)\n\x03raw\x12\"\n\x03raw\x12\x0c.rawImageMsg\x1a\x0b.imageReply\"\x00\x32\"\n\x03\x61\x64\x64\x12\x1b\n\x03\x61\x64\x64\x12\x07.addMsg\x1a\t.addReply\"\x00\x32\x30\n\x03\x64ot\x12)\n\x03\x64ot\x12\x0e.dotProductMsg\x1a\x10.dotProductReply\"\x00\x32\x32\n\x07jsonimg\x12\'\n\x07jsonimg\x12\r.jsonImageMsg\x1a\x0b.imageReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lab6_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RAWIMAGEMSG._serialized_start=14
  _RAWIMAGEMSG._serialized_end=40
  _ADDMSG._serialized_start=42
  _ADDMSG._serialized_end=72
  _DOTPRODUCTMSG._serialized_start=74
  _DOTPRODUCTMSG._serialized_end=111
  _JSONIMAGEMSG._serialized_start=113
  _JSONIMAGEMSG._serialized_end=140
  _ADDREPLY._serialized_start=142
  _ADDREPLY._serialized_end=165
  _DOTPRODUCTREPLY._serialized_start=167
  _DOTPRODUCTREPLY._serialized_end=204
  _IMAGEREPLY._serialized_start=206
  _IMAGEREPLY._serialized_end=249
  _RAW._serialized_start=251
  _RAW._serialized_end=292
  _ADD._serialized_start=294
  _ADD._serialized_end=328
  _DOT._serialized_start=330
  _DOT._serialized_end=378
  _JSONIMG._serialized_start=380
  _JSONIMG._serialized_end=430
# @@protoc_insertion_point(module_scope)
